import = [
  "~/.config/alacritty/themes/themes/Cobalt2.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
normal.family = "FiraCode Nerd Font"
size = 15
# offset.y = 1

[selection]
save_to_clipboard = true

[window]
dimensions = {columns = 170, lines = 100}
padding = { x = 7, y = 3 }
opacity = 0.7
blur = false
decorations = "Buttonless"
option_as_alt = "Both"

[colors]
draw_bold_text_with_bright_colors = true


 
