import = [
  "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
normal.family = "Iosevka Nerd Font"
size = 17
# offset.y = 1

[selection]
save_to_clipboard = true

[window]
dimensions = {columns = 170, lines = 100}
padding = { x = 10, y = 3 }
opacity = 0.9
blur = false
decorations = "Buttonless"
option_as_alt = "Both"

[colors]
draw_bold_text_with_bright_colors = true



