vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.mouse = "a"
vim.opt.clipboard = "unnamedplus"
vim.opt.showtabline = 0
vim.opt.expandtab = true
vim.opt.shiftwidth = 4
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.smartindent = true
vim.opt.autoindent = true
vim.opt.cmdheight = 2
vim.opt.wrap = false
--text wrap width
vim.opt.textwidth = 100
vim.opt.swapfile = false
vim.opt.termguicolors = true
vim.opt.colorcolumn = "120"
